### ISSUE TITLE
Zoom Level

### ISSUE THREAD

**Issue by diegordrgs** [mapbox/mbxmapkit#141]
How can I change the zoom level when the map loads?

**Comment by incanus** [comment]
@diegordrgs If it's a Mapbox-hosted map, you can set this online and `includeMetadata:YES` (the default) in order to capture these settings in the overlay setup. 

You can also check out the `-[MKMapView mbx_setCenterCoordinate:zoomLevel:animated:]` that we've added for setting the zoom level directly.
