### ISSUE TITLE
No support for OS X anymore?

### ISSUE THREAD

**Issue by syedhali** [mapbox/mbxmapkit#151]
The most recent podspec 0.7.0 doesn't support OS X anymore. Was this intentional?

**Comment by wsnook** [comment]
@syedhali, For some backstory on OS X support, you might want to take a look at https://github.com/mapbox/mbxmapkit/issues/78 and
https://github.com/mapbox/mbxmapkit/pull/59. I haven't been involved much with MBXMapKit recently, so I'm not totally up on recent changes. However, there was a point last spring when we decided to stop worrying about OS X support in order to ship sooner on iOS. It shouldn't be too hard to get the code working on OS X though. The big issue was the amount of effort required to maintain two different sample apps. The differences are mainly `#ifdef`'s to pick between `NS<something>` vs. `UI<something>` for classes which are not present on both platforms

**Comment by wsnook** [comment]
@syedhali Also, I just noticed these two commits that @incanus made on February 3
- https://github.com/mapbox/mbxmapkit/commit/764a3b2b25e1886cfa543946c95b1dae488644b6: remove mention of OS X from podspec
- https://github.com/mapbox/mbxmapkit/commit/d485ef0584b66eded4590fe899d3ec3ba2e12d4e: remove official OS X support from podspec

Judging from those commit messages, it seems like the answer to your question is probably "yes".

**Comment by incanus** [comment]
Yes, it was intentional, but you are welcome to modify a copy of the podspec to give it a shot yourself, and PRs on any release to improve OS X support are welcome. We haven't ripped out any OS X code or anything, but rather the idea was that we wouldn't have to test on OS X before releases, per [our platform note](https://github.com/mapbox/mbxmapkit#platforms). Basically what @wsnook said above.
